import Header from "../../../components/header";
import Middow from "../../../components/middow";

export const metadata = {
  title: "dunkab ventures",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      <div>
        <Middow />
        <div className="sticky top-0 z-10">
            <Header />
        </div>
        {children}
      </div>
    </div>
  );
}
